### PR TITLE
Add SocialSecurity.java

### PR DESCRIPTION
**Pull request by Israel-SanchezH**

### CODE REVIEW

**Review by israels-github — COMMENTED** [review]
I think, it should be an interface

**Comment by Israel-SanchezH** [comment]
No, it is a class

**Comment by israels-github** [comment]
Then, please define the class

**Review by Israel-SanchezH — COMMENTED** [review]
Please, check the definition of the class

**Review by israels-github — CHANGES_REQUESTED** [review]
Please define a constructor

**Review by Israel-SanchezH — COMMENTED** [review]
Default constructor defined

**Review by israels-github — APPROVED** [review]
Approved

**Pull request merged**
