### PR TITLE
Department

### PR DESCRIPTION
**Pull request by Israel-SanchezH**
Please define class

### CODE REVIEW

**Review by Israel-SanchezH — COMMENTED** [review]
Class defined please check

**Comment by israels-github** [comment]
Please define class

**Comment by Israel-SanchezH** [comment]
Class defined, thanks

**Review by israels-github — CHANGES_REQUESTED** [review]
Please define a second constructor

**Review by Israel-SanchezH — COMMENTED** [review]
Second constructor defined, thanks

**Review by israels-github — COMMENTED** [review]
Looks great!!!!

**Review by israels-github — APPROVED** [review]
The pull request has been approved

**Pull request merged**
